const roles=["Senior Android Engineer","Mobile Architect","Android Engineering Lead","Kotlin & Jetpack Compose Specialist","Mobile Performance & Security Engineer"];let roleIndex=0;const role=document.getElementById("roleText");setInterval(()=>{role.style.opacity="0";setTimeout(()=>{roleIndex=(roleIndex+1)%roles.length;role.textContent=roles[roleIndex];role.style.opacity="1"},180)},2800);

const spotlight=document.getElementById("spotlight");window.addEventListener("mousemove",e=>{document.documentElement.style.setProperty("--mx",e.clientX+"px");document.documentElement.style.setProperty("--my",(e.clientY+window.scrollY)+"px");if(spotlight)spotlight.style.background=`radial-gradient(600px circle at ${e.clientX}px ${e.clientY}px,rgba(59,130,246,.035),transparent 80%)`},{passive:true});

const navLinks=[...document.querySelectorAll("[data-nav]")];navLinks.forEach(a=>a.addEventListener("click",e=>{const href=a.getAttribute("href");if(href?.startsWith("#")){e.preventDefault();document.querySelector(href)?.scrollIntoView({behavior:"smooth"})}}));
const sections=[...document.querySelectorAll("main section[id]")];const links=[...document.querySelectorAll(".desktop-nav a")];const io=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){links.forEach(l=>l.classList.toggle("active",l.getAttribute("href")==="#"+entry.target.id))}}),{rootMargin:"-35% 0px -55% 0px"});sections.forEach(s=>io.observe(s));

document.querySelectorAll(".section,.project-card,.job,.skill-group,.recognition-card").forEach((el,i)=>{el.classList.add("reveal");el.style.transitionDelay=(i%5)*50+"ms"});const ro=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");ro.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll(".reveal").forEach(e=>ro.observe(e));

const copy=()=>{navigator.clipboard?.writeText("chakraborty.dipanjan07@gmail.com");const t=document.getElementById("emailText");if(t){const old=t.textContent;t.textContent="Copied!";setTimeout(()=>t.textContent=old,1800)}};document.getElementById("copyEmail").onclick=copy;document.getElementById("copyEmail2").onclick=copy;

document.querySelectorAll("#projectTabs button").forEach(btn=>btn.onclick=()=>{document.querySelectorAll("#projectTabs button").forEach(b=>b.classList.remove("active"));btn.classList.add("active");const filter=btn.dataset.filter;document.querySelectorAll(".project-card").forEach(card=>card.classList.toggle("hide",filter!=="all"&&card.dataset.category!==filter))});

const palette=document.getElementById("palette"),input=document.getElementById("paletteInput");document.getElementById("commandBtn").onclick=()=>{palette.classList.add("open");palette.setAttribute("aria-hidden","false");input.focus()};palette.addEventListener("click",e=>{if(e.target===palette)palette.classList.remove("open")});document.querySelectorAll(".palette button").forEach(b=>b.onclick=()=>{palette.classList.remove("open");document.querySelector(b.dataset.target)?.scrollIntoView({behavior:"smooth"})});document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();palette.classList.toggle("open");if(palette.classList.contains("open"))input.focus()}if(e.key==="Escape")palette.classList.remove("open")});

if(!matchMedia("(prefers-reduced-motion: reduce)").matches){document.querySelectorAll(".project-card").forEach(card=>{card.addEventListener("pointermove",e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(900px) rotateX(${(-y*1.8).toFixed(2)}deg) rotateY(${(x*2.2).toFixed(2)}deg) translateY(-5px)`});card.addEventListener("pointerleave",()=>card.style.transform="")})}

const langBtn=document.getElementById("langBtn");if(langBtn){langBtn.addEventListener("click",()=>{langBtn.textContent=langBtn.textContent.includes("EN")?"◎ EN":"◎ EN"})}
